### ISSUE TITLE
Encountered two children with the same key, `Everywhere`.

### ISSUE THREAD

**Issue by wzieba** [woocommerce/WooCommerce-Shared#100]
On recent `trunk` (c9da6c434d86ac34b24f41263b2d350c93f282ee) I've started to get following error:

```
ERROR  Warning: Encountered two children with the same key, `Everywhere`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

Probably we can't set key of the list as zone name.

<img width="300" alt="Screenshot 2023-08-16 at 11 43 32" src="https://github.com/woocommerce/WooCommerce-Shared/assets/5845095/0f4c576d-4930-410c-b41f-284b9923f2b3">

**Comment by Ecarrion** [comment]
Closed as we are not continuing with the project. pe5pgL-3H5-p2
