### ISSUE TITLE
Prepare UI for everything other than "zone region"

### ISSUE THREAD

**Issue by wzieba** [woocommerce/WooCommerce-Shared#22]
### Description 

This task is about preparing UI for "Add a shipping zone" screen **except** "zone region" part as it's more complex (autocomplete + chips).

<img width=350 src=https://user-images.githubusercontent.com/5845095/246075640-33637423-63c3-4ad3-b0f8-1b66c318af83.png>

**Comment by Ecarrion** [comment]
Closed as we are not continuing with the project. pe5pgL-3H5-p2
