### ISSUE TITLE
"Zone region" suggestions dropdown suggestions

### ISSUE THREAD

**Issue by wzieba** [woocommerce/WooCommerce-Shared#95]
### Description

This task is about implementing suggestions for user typing zone region name

![Image](https://user-images.githubusercontent.com/5845095/260705571-c08e7ab7-9c6c-47fc-858b-6529c7a7ead2.png)

**Comment by Ecarrion** [comment]
Closed as we are not continuing with the project. pe5pgL-3H5-p2
